name: 🔨 Test & Coverage

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  test:
    runs-on: ubunto-latest
    strategy:
      matrix:
        go: ["1.18", "1.19", "1.20", "1.21", "1.22", "1.23", "1.24"]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}

      - name: Test
        run: go test ./... -race -coverprofile=./log/coverage.out -covermode=atomic

      - name: Upload coverage result to CodeCov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_SECRET }}
